# https://github.com/dockersamples/slack-clone-docker

FROM node:16

WORKDIR /app 

COPY ./package.json ./package.json 
COPY ./postcss.config.js ./postcss.config.js  
COPY ./tailwind.config.js ./tailwind.config.js     
COPY ./vite.config.js ./vite.config.js 
COPY ./.env ./.env

COPY ./src ./src 

RUN npm install 

EXPOSE 5173

CMD ["npm", "run", "dev"]
