FROM node:16

WORKDIR /app 

COPY ./package.json ./package.json 
COPY ./models ./models          
COPY ./routes ./routes                            
COPY ./services ./services
COPY ./utils ./utils
COPY ./config ./config
COPY ./.env ./.env
COPY ./index.js ./index.js

RUN npm install
RUN npm install -g nodemon

EXPOSE 8080

CMD ["nodemon", "start"]